# My Variables
@contentType = application/json
# @baseurl = https://backend-v2.onrender.com/api
@baseurl = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzhlM2RiMDQ3YjkzZmM4NDA2NjFjMzMiLCJpYXQiOjE2NzAyNjYyODgsImV4cCI6MTY3MDUyNTQ4OH0.V2WnbaSHgnnjAi-NRAZrZU3_BgVtodqr2gWSh5DC20Q


### login
POST  {{baseurl}}/user/login
Content-Type: {{contentType}}

{
    "email": "mirja@mirja.fi",
    "password": "45RFgh##@$"
}


### POST Request
POST {{baseurl}}/recipes/
Content-Type: {{contentType}}
Authorization: bearer {{token}}

{
    "recipeName":"Kukkakaalilaatikko",
    "ingredients":[{"ingredient":"kukkakaali","amount":3,"unit":"kpl"}],
    "instructions":"Pilko kukkakaalit ja karamellisoi ne!"
}


### GET Request
GET {{baseurl}}/recipes/
Content-Type: {{contentType}}
Authorization: bearer {{token}}

### Signup
POST  {{baseurl}}/user/signup
Content-Type: {{contentType}}

{
    "email": "matti55@matti.fi",
    "password": "R3g5T7#gh"
}

### login
POST  {{baseurl}}/user/login
Content-Type: {{contentType}}

{
    "email": "matti55@matti.fi",
    "password": "R3g5T7#gh"
}
